# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=256)),
                ('coin_name', models.CharField(max_length=256)),
                ('coin_symbol', models.CharField(max_length=16)),
                ('lastcount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TempCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=256)),
                ('coin_symbol', models.CharField(max_length=16)),
                ('pc_diff', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
