# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedditCryptoCount', '0003_auto_20171124_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastcount',
            name='id_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastcount',
            name='name_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastcount',
            name='symbol_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
