# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedditCryptoCount', '0004_auto_20171124_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastcount',
            name='thiscount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
