# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedditCryptoCount', '0005_lastcount_thiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastcount',
            name='pc_diff_plus_minus',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
