# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedditCryptoCount', '0006_lastcount_pc_diff_plus_minus'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastcount',
            name='lastcount2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastcount',
            name='lastcount3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastcount',
            name='lastcount4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastcount',
            name='lastcount5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastcount',
            name='lastcount6',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
