# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedditCryptoCount', '0007_auto_20171125_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastcount',
            name='pc_diff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
