# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedditCryptoCount', '0008_auto_20171125_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastcount',
            old_name='id_count',
            new_name='coin_count',
        ),
        migrations.RemoveField(
            model_name='lastcount',
            name='name_count',
        ),
        migrations.RemoveField(
            model_name='lastcount',
            name='symbol_count',
        ),
    ]
